package com.p3t3rp3r3z.navlib.ui

import android.os.Bundle
import android.view.View
import androidx.appcompat.app.AppCompatActivity
import androidx.navigation.findNavController
import androidx.navigation.fragment.NavHostFragment
import com.p3t3rp3r3z.navlib.R

class NavHostActivity :   AppCompatActivity() {
    val bundle = Bundle().apply {
        //note I'm overloading the value that is defaulted for fragmentOneString in the nav_graph,
        //so I need to use the same key that it would generate. you can see this in the
        //DestinationFragmentOneArgs class that was auto generated by using the safeArgs plugin
        putString("fragmentOneString", "Even though we can set a default argument," +
                "\nthis string was passed in from the host activity, as a demonstration.")
    }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.navhost_activity)
        val navHostFragment =
            supportFragmentManager.findFragmentById(R.id.nav_host_fragment) as NavHostFragment
        navHostFragment.navController.setGraph(R.navigation.nav_graph, bundle)
        /*
        * NavController manages app navigation within a NavHost
        * a NavHost is a single context or container for navigation
         */
        val navControllerOne = navHostFragment.navController

    }
}